const cube={
  "version" : "0.1.0",

  "comment" : "Generated by MeshLab JSON Exporter",

  "id"      : 1,
  "name"    : "mesh",

  "vertices" :
  [
    {
      "name"       : "position_buffer",
      "size"       : 3,
      "type"       : "float32",
      "normalized" : false,
      "values"     :
      [
        -100, 100, -100, 100, 100, 100, 100, 100, -100, -100, -100, 100, 100, -100, 100, -100, 100, 100, -100, -100, -100, 100, -100, -100
      ]
    },

    {
      "name"       : "normal_buffer",
      "size"       : 3,
      "type"       : "float32",
      "normalized" : false,
      "values"     :
      [
        -1.5708, 1.5708, -1.5708, 1.5708, 1.5708, 1.5708, 1.5708, 1.5708, -1.5708, -1.5708, -1.5708, 1.5708, 1.5708, -1.5708, 1.5708, -1.5708, 1.5708, 1.5708, -1.5708, -1.5708, -1.5708, 1.5708, -1.5708, -1.5708
      ]
    }
  ],

  "connectivity" :
  [
    {
      "name"      : "triangles",
      "mode"      : "triangles_list",
      "indexed"   : true,
      "indexType" : "uint32",
      "indices"   :
      [
        0, 1, 2, 1, 3, 4, 5, 6, 3, 7, 3, 6, 2, 4, 7, 0, 7, 6, 0, 5, 1, 1, 5, 3, 5, 0, 6, 7, 4, 3,
        2, 1, 4, 0, 2, 7
      ]
    }
  ],

  "mapping" :
  [
    {
      "name"       : "standard",
      "primitives" : "triangles",
      "attributes" :
      [
        {
          "source"   : "position_buffer",
          "semantic" : "position",
          "set"      : 0
        },
        {
          "source"   : "normal_buffer",
          "semantic" : "normal",
          "set"      : 0
        }
      ]
    }
  ],

  "custom" : null
}

const shapeCube = new Shape(cube.vertices[0].values, cube.connectivity[0].indices, cube.vertices[0].values)
